/**
 * militaryRfData.ts — Military RF Communication Bands Database
 * Sources:
 *   - "Global Military Spectrum Dominance" research PDF
 *   - sigidwiki.com/wiki/Category:Military (129 military signals)
 *   - priyom.org (military stations, number stations)
 *   - radioreference.com (HF Military Communications)
 * 
 * Structured data for the Military RF Intelligence reference panel.
 */

export type BandCategory = "VLF" | "LF" | "MF" | "HF" | "VHF" | "UHF";
export type Operator = "USA" | "Russia" | "China" | "NATO" | "Israel" | "Japan" | "Australia" | "Canada" | "France" | "UK" | "Iran" | "Sweden" | "International";
export type SignalType = "voice" | "digital" | "beacon" | "navigation" | "radar" | "marker" | "numbers" | "broadcast" | "scrambler" | "datalink";

export interface MilitaryFrequency {
  id: string;
  frequency: string;
  frequencyKhz: number;
  system: string;
  designation: string;
  operator: Operator;
  band: BandCategory;
  signalType: SignalType;
  description: string;
  classification: string;
  power?: string;
  location?: string;
  notes?: string;
  source?: string;
  modulation?: string;
  bandwidth?: string;
  status?: "active" | "inactive" | "unknown";
}

export interface BandSection {
  id: BandCategory;
  label: string;
  range: string;
  description: string;
  color: string;
  propagation: string;
}

export interface WaveformInfo {
  id: string;
  name: string;
  standard: string;
  description: string;
  bandwidth: string;
  users: string;
  visualId: string;
}

export const BAND_SECTIONS: BandSection[] = [
  {
    id: "VLF",
    label: "VLF",
    range: "3 kHz – 30 kHz",
    description: "Very Low Frequency — Submarine Strategic Command",
    color: "#a855f7",
    propagation: "Penetrates seawater 10-20m — the only way to reach submerged submarines without surfacing",
  },
  {
    id: "LF",
    label: "LF",
    range: "30 kHz – 300 kHz",
    description: "Low Frequency — Navigation & Timing",
    color: "#f59e0b",
    propagation: "Ground Wave — signals hug Earth's curvature for maritime/coastal reach",
  },
  {
    id: "MF",
    label: "MF",
    range: "300 kHz – 3 MHz",
    description: "Medium Frequency Naval Bridge",
    color: "#06b6d4",
    propagation: "Ground Wave over seawater — reliable fleet coordination over hundreds of miles",
  },
  {
    id: "HF",
    label: "HF",
    range: "3 MHz – 30 MHz",
    description: "Strategic High Frequency Global Battlefield",
    color: "#ef4444",
    propagation: "Sky Wave — ionospheric reflection enables intercontinental range without satellites",
  },
  {
    id: "VHF",
    label: "VHF",
    range: "30 MHz – 300 MHz",
    description: "Tactical & Surveillance",
    color: "#22c55e",
    propagation: "Line-of-Sight / Diffraction — penetrates foliage, preferred for armor & infantry",
  },
  {
    id: "UHF",
    label: "UHF",
    range: "300 MHz – 3 GHz",
    description: "Satellite, Radar & Space Surveillance",
    color: "#ec4899",
    propagation: "Line-of-Sight — used for satellite links, radar, and high-bandwidth tactical data",
  },
];

export const WAVEFORMS: WaveformInfo[] = [
  {
    id: "stanag4285",
    name: "STANAG 4285",
    standard: "NATO HF Modem",
    description: "Phase Shift Keying (PSK8) on 1800 Hz subcarrier. Standard NATO HF data waveform for 1200/2400/3600 bps.",
    bandwidth: "2.75 kHz",
    users: "NATO forces worldwide",
    visualId: "Solid block of noise with distinct edges, preamble tones at start",
  },
  {
    id: "stanag4539",
    name: "STANAG 4539",
    standard: "NATO HDR Serial",
    description: "High Data Rate serial PSK/QAM signal reaching up to 9600 bps. Also known as MIL-STD-188-110B/C Appendix C.",
    bandwidth: "3 kHz",
    users: "NATO, USA",
    visualId: "Dense PSK/QAM signal with characteristic preamble",
  },
  {
    id: "stanag4197",
    name: "STANAG 4197",
    standard: "NATO ANDVT",
    description: "QPSK OFDM signal used in ANDVT modems for encrypted digital voice over HF.",
    bandwidth: "2.3 kHz",
    users: "NATO forces",
    visualId: "OFDM tones visible as parallel lines on waterfall",
  },
  {
    id: "ale2g",
    name: "2G ALE",
    standard: "MIL-STD-188-141A",
    description: "Automatic Link Establishment using 8-tone MFSK. Automates frequency selection based on ionospheric conditions.",
    bandwidth: "~2 kHz",
    users: "USA, NATO, PLA, Israel, Japan, worldwide",
    visualId: "Distinctive chirp sound, easily recognized on waterfall",
  },
  {
    id: "ale3g",
    name: "3G ALE (ARCS)",
    standard: "STANAG 4538 / MIL-STD-188-141B App C",
    description: "Fast, robust linking protocol for high-priority traffic. Next generation ALE with wideband capabilities.",
    bandwidth: "~6 kHz",
    users: "NATO, USA",
    visualId: "Wider, synchronized bursts of data",
  },
  {
    id: "milstd110serial",
    name: "MIL-STD-188-110 Serial",
    standard: "US DoD HF Standard",
    description: "Serial PSK mode for HF data and voice. Can transmit at various speeds with interleaving for optimal propagation.",
    bandwidth: "2.75 kHz",
    users: "USA, NATO, worldwide",
    visualId: "Single-carrier PSK with characteristic sync preamble",
  },
  {
    id: "milstd110_16tone",
    name: "MIL-STD-188-110 App A 16-Tone",
    standard: "US DoD OFDM",
    description: "16-tone OFDM PSK signal for parallel data transmission. Being phased out as of 110C revision.",
    bandwidth: "2.1 kHz",
    users: "USA, NATO",
    visualId: "16 parallel tones visible on waterfall",
  },
  {
    id: "milstd110_39tone",
    name: "MIL-STD-188-110 App B 39-Tone",
    standard: "US DoD Wideband OFDM",
    description: "39-tone OFDM DQPSK mode for high-throughput data and voice transmission.",
    bandwidth: "2.4 kHz",
    users: "USA, NATO",
    visualId: "Dense 39-tone OFDM pattern on waterfall",
  },
  {
    id: "t600",
    name: "T-600",
    standard: "Russian FSK",
    description: "50 Baud Frequency Shift Keying mode used by Russian strategic networks.",
    bandwidth: "~500 Hz",
    users: "Russian Federation",
    visualId: "Narrow FSK signal with steady shift",
  },
  {
    id: "at3104",
    name: "AT-3104 / CIS-12",
    standard: "Russian Multi-tone PSK",
    description: "12-tone PSK Russian military multi-channel modem. Also known as MS5, FIRE, AT-3004D.",
    bandwidth: "~3.1 kHz",
    users: "Russian Federation",
    visualId: "Multiple parallel tones visible on waterfall",
  },
  {
    id: "cis3000",
    name: "CIS-3000",
    standard: "Russian 8-PSK Modem",
    description: "8-PSK Data Modem at 3000 Baud (max 9000 bps). Acts as ALE for CIS-128 and CIS MFSK-68.",
    bandwidth: "3.4 kHz",
    users: "Russian Federation",
    visualId: "Dense PSK signal with characteristic sync pattern",
  },
  {
    id: "cis128",
    name: "CIS-128",
    standard: "Russian OFDM",
    description: "128-channel OFDM mode with one off channel in center. Supports PSK, OFDM, and QAM modulations.",
    bandwidth: "3.1–6.1 kHz",
    users: "Russian Federation",
    visualId: "Wide OFDM signal split into two 64-channel halves",
  },
  {
    id: "link11",
    name: "Link-11 (TADIL-A)",
    standard: "STANAG 5511 / MIL-STD-6011",
    description: "NATO Tactical Data Link for Maritime Tactical Data Exchange. PSK-based with 2.5-6 kHz bandwidth.",
    bandwidth: "2.5–6 kHz",
    users: "NATO, US Military",
    visualId: "Characteristic PSK bursts with regular timing",
  },
  {
    id: "othr",
    name: "29B6 Kontayner",
    standard: "Russian OTHR",
    description: "Bi-static Over-the-Horizon Radar sweeping 6–32 MHz for aircraft/missile detection. Uses 150 antenna masts.",
    bandwidth: "3.5–28 kHz wideband sweep",
    users: "Russian Federation",
    visualId: "Repetitive 10–50 Hz thump, helicopter-like noise",
  },
  {
    id: "jorn",
    name: "JORN",
    standard: "Australian OTHR",
    description: "Jindalee Operational Radar Network. Unique intro tone before radar bursts. Covers northern approaches to Australia.",
    bandwidth: "3–60 kHz",
    users: "Australia",
    visualId: "Distinctive intro tone followed by FMCW sweeps",
  },
  {
    id: "rothr",
    name: "ROTHR (AN/TPS-71)",
    standard: "US Navy OTHR",
    description: "Relocatable Over-the-Horizon Radar using bistatic ionospheric backscattering for wide area surveillance.",
    bandwidth: "4–100 kHz",
    users: "US Navy",
    visualId: "FMCW sweeps with variable bandwidth",
  },
  {
    id: "thales3000",
    name: "Thales Système 3000",
    standard: "French Military Modem",
    description: "Multi-mode HF modem supporting PSK, MFSK, voice scrambling, and Skyhopper frequency hopping.",
    bandwidth: "2–3 kHz",
    users: "France, NATO",
    visualId: "Unique preamble format with PSK/MFSK transitions",
  },
  {
    id: "salamandre",
    name: "Thales SALAMANDRE",
    standard: "French Wideband HF",
    description: "Uses up to 16 separate HF channels for high datarate military communications on modified STANAG-4539.",
    bandwidth: "Up to 150 kHz aggregate",
    users: "France, NATO",
    visualId: "Multiple parallel STANAG-4539 channels",
  },
  {
    id: "akkord",
    name: "AKKORD-SS-PD",
    standard: "Russian Tactical Datalink",
    description: "MSK-based datalink used during the invasion of Ukraine. Akkord-165 is the most recent version.",
    bandwidth: "1.2 kHz",
    users: "Russian Federation",
    visualId: "Narrow MSK signal on fixed frequency",
  },
];

export const MILITARY_FREQUENCIES: MilitaryFrequency[] = [
  // =============================================
  // === VLF BAND (3–30 kHz) — Submarine Command
  // =============================================
  {
    id: "rsdn20",
    frequency: "11.91–14.88 kHz",
    frequencyKhz: 13.4,
    system: "RSDN-20 (Alpha)",
    designation: "Russian Hyperbolic Nav",
    operator: "Russia",
    band: "VLF",
    signalType: "navigation",
    description: "Russian hyperbolic radio navigation system for ships, submarines and aircraft in the northern hemisphere.",
    classification: "Strategic",
    power: "Megawatt-class",
    source: "sigidwiki",
    status: "active",
  },
  {
    id: "rdl-vlf",
    frequency: "18.1 kHz",
    frequencyKhz: 18.1,
    system: "RDL VLF",
    designation: "RDL Krasnodar",
    operator: "Russia",
    band: "VLF",
    signalType: "digital",
    description: "Russian VLF station in Krasnodar. One of few VLF stations that changes modes during routine transmissions.",
    classification: "Strategic",
    location: "Krasnodar, Russia",
    source: "sigidwiki",
    modulation: "FSK, CW-FSK",
    bandwidth: "300 Hz",
    status: "active",
  },
  {
    id: "nwc",
    frequency: "19.8 kHz",
    frequencyKhz: 19.8,
    system: "VLF Submarine Command",
    designation: "NWC",
    operator: "Australia",
    band: "VLF",
    signalType: "digital",
    description: "Naval Communication Station Harold E. Holt. Used jointly by Australian and US navies for encrypted orders to submarines in the Pacific.",
    classification: "Strategic",
    power: "Megawatt-class",
    location: "North West Cape, Australia",
    source: "sigidwiki",
    modulation: "FSK",
    bandwidth: "300 Hz",
    status: "active",
  },
  {
    id: "icv",
    frequency: "20.27 kHz",
    frequencyKhz: 20.27,
    system: "NATO VLF",
    designation: "ICV Tavolara",
    operator: "NATO",
    band: "VLF",
    signalType: "digital",
    description: "NATO-operated VLF transmitter on the island of Tavolara, Sardinia, Italy for submarine communications.",
    classification: "Strategic",
    location: "Tavolara, Sardinia, Italy",
    source: "sigidwiki",
    modulation: "MSK",
    status: "active",
  },
  {
    id: "npm",
    frequency: "21.4 kHz",
    frequencyKhz: 21.4,
    system: "VLF Submarine Command",
    designation: "NPM",
    operator: "USA",
    band: "VLF",
    signalType: "digital",
    description: "Naval Radio Transmitting Facility sends encrypted commands to submerged US naval submarines in the Pacific.",
    classification: "Strategic",
    power: "Megawatt-class",
    location: "Lualualei, Hawaii",
    source: "sigidwiki",
    modulation: "FSK",
    bandwidth: "300 Hz",
    status: "active",
  },
  {
    id: "naa",
    frequency: "24.0 kHz",
    frequencyKhz: 24,
    system: "VLF Submarine Command",
    designation: "NAA Cutler",
    operator: "USA",
    band: "VLF",
    signalType: "digital",
    description: "Cutler, Maine — The most powerful VLF station in the world. Sends encrypted MSK/FSK data to SSBNs.",
    classification: "Strategic",
    power: "Megawatt-class (2 MW)",
    location: "Cutler, Maine",
    source: "sigidwiki",
    modulation: "MSK, FSK",
    bandwidth: "300 Hz",
    status: "active",
  },
  {
    id: "nlk",
    frequency: "24.8 kHz",
    frequencyKhz: 24.8,
    system: "VLF Submarine Command",
    designation: "NLK Jim Creek",
    operator: "USA",
    band: "VLF",
    signalType: "digital",
    description: "Jim Creek Naval Radio Station used by the US Navy to transmit commands to distant submarines.",
    classification: "Strategic",
    power: "Megawatt-class (1.2 MW)",
    location: "Jim Creek, Washington",
    source: "sigidwiki",
    modulation: "MSK",
    bandwidth: "300 Hz",
    status: "active",
  },
  {
    id: "nml",
    frequency: "25.2 kHz",
    frequencyKhz: 25.2,
    system: "VLF Submarine Command",
    designation: "NML",
    operator: "USA",
    band: "VLF",
    signalType: "digital",
    description: "Naval Radio Transmitter Facility transmits encrypted commands to submerged US submarines.",
    classification: "Strategic",
    location: "LaMoure, North Dakota",
    source: "sigidwiki",
    modulation: "FSK",
    bandwidth: "300 Hz",
    status: "active",
  },
  {
    id: "nov",
    frequency: "26.9 kHz",
    frequencyKhz: 26.9,
    system: "TACAMO",
    designation: "NOV",
    operator: "USA",
    band: "VLF",
    signalType: "digital",
    description: "TACAMO (Take Charge And Move Out) — backup communications to US nuclear submarine fleet via E-6B aircraft with 2.5-mile trailing wire antennas.",
    classification: "Strategic",
    power: "200 kW airborne",
    source: "sigidwiki",
    notes: "Short pings every few seconds from rotating fleet of E-6B jets at 35,000 ft",
    status: "active",
  },
  {
    id: "shr",
    frequency: "38 kHz",
    frequencyKhz: 38,
    system: "Swedish Navy VLF",
    designation: "SHR",
    operator: "Sweden",
    band: "VLF",
    signalType: "digital",
    description: "Swedish Navy submarine communication transmitter sharing antenna with SAQ Grimeton.",
    classification: "Strategic",
    location: "Grimeton, Sweden",
    source: "sigidwiki",
    modulation: "MSK",
    status: "active",
  },
  {
    id: "sas-src",
    frequency: "40.4 kHz",
    frequencyKhz: 40.4,
    system: "Swedish Navy VLF",
    designation: "SAS/SRC",
    operator: "Sweden",
    band: "VLF",
    signalType: "digital",
    description: "Swedish Navy submarine communication transmitter sharing antenna with SAQ Grimeton Radio.",
    classification: "Strategic",
    location: "Grimeton, Sweden",
    source: "sigidwiki",
    modulation: "MSK",
    status: "active",
  },

  // =============================================
  // === LF BAND (30–300 kHz) — Navigation & Timing
  // =============================================
  {
    id: "chayka",
    frequency: "100 kHz",
    frequencyKhz: 100,
    system: "Chayka",
    designation: "Loran-C Counterpart",
    operator: "Russia",
    band: "LF",
    signalType: "navigation",
    description: "Russian military navigation and timing synchronization. Terrestrial fallback for GPS-denied environments.",
    classification: "Strategic",
    power: "Megawatt-class",
    status: "active",
  },
  {
    id: "gyn2-gbr",
    frequency: "81 kHz",
    frequencyKhz: 81,
    system: "GYN2 GBR",
    designation: "Royal Navy VLF",
    operator: "UK",
    band: "LF",
    signalType: "digital",
    description: "Ministry of Defence transmitting site used by British Navy to transmit encrypted messages to submarines at sea.",
    classification: "Strategic",
    location: "Anthorn, United Kingdom",
    source: "sigidwiki",
    status: "active",
  },
  {
    id: "stanag5065",
    frequency: "50–160 kHz",
    frequencyKhz: 105,
    system: "STANAG 5065",
    designation: "NATO LF Shore-to-Ship",
    operator: "NATO",
    band: "LF",
    signalType: "digital",
    description: "Minimum Standards for Naval Low Frequency Shore-To-Ship Surface Broadcast Systems. Two protocols: FSK75 and MSK300.",
    classification: "Strategic",
    source: "sigidwiki",
    modulation: "FSK, MSK",
    bandwidth: "235–360 Hz",
    status: "active",
  },
  {
    id: "graves",
    frequency: "143.05 MHz",
    frequencyKhz: 143050,
    system: "GRAVES",
    designation: "Space Surveillance",
    operator: "France",
    band: "VHF",
    signalType: "radar",
    description: "Grand Réseau Adapté à la Veille Spatiale — French space-surveillance system for low-orbit satellites up to 1000km.",
    classification: "Strategic",
    location: "Dijon, France",
    source: "sigidwiki",
    bandwidth: "1 kHz",
    status: "active",
  },
  {
    id: "ndb-ytr",
    frequency: "215 kHz",
    frequencyKhz: 215,
    system: "NDB",
    designation: "YTR",
    operator: "Canada",
    band: "LF",
    signalType: "beacon",
    description: "Military Non-Directional Beacon at CFB Trenton, Ontario.",
    classification: "Navigation",
    power: "100W",
    location: "CFB Trenton, Ontario",
  },
  {
    id: "ndb-da",
    frequency: "223 kHz",
    frequencyKhz: 223,
    system: "NDB",
    designation: "DA",
    operator: "USA",
    band: "LF",
    signalType: "beacon",
    description: "Military NDB at Davison Army Airfield, Fort Belvoir.",
    classification: "Navigation",
    power: "50W",
    location: "Fort Belvoir, Virginia",
  },
  {
    id: "ndb-dd",
    frequency: "253 kHz",
    frequencyKhz: 253,
    system: "NDB",
    designation: "DD",
    operator: "USA",
    band: "LF",
    signalType: "beacon",
    description: "Military NDB at Rickenbacker ANG Base, Ohio.",
    classification: "Navigation",
    power: "25W",
    location: "Rickenbacker ANG Base, Ohio",
  },

  // =============================================
  // === MF BAND (300 kHz – 3 MHz)
  // =============================================
  {
    id: "ndb-ab",
    frequency: "360 kHz",
    frequencyKhz: 360,
    system: "NDB",
    designation: "AB",
    operator: "Russia",
    band: "MF",
    signalType: "beacon",
    description: "Military/Dual Use NDB at Abakan.",
    classification: "Navigation",
    location: "Abakan, Russia",
  },
  {
    id: "ndb-ft",
    frequency: "365 kHz",
    frequencyKhz: 365,
    system: "NDB",
    designation: "FT",
    operator: "USA",
    band: "MF",
    signalType: "beacon",
    description: "High-power military NDB at NAS JRB Fort Worth, Texas.",
    classification: "Navigation",
    power: "400W",
    location: "NAS JRB Fort Worth, Texas",
  },
  {
    id: "ndb-wlm",
    frequency: "365 kHz",
    frequencyKhz: 365,
    system: "NDB",
    designation: "WLM",
    operator: "Australia",
    band: "MF",
    signalType: "beacon",
    description: "High-power military NDB at RAAF Base Williamtown.",
    classification: "Navigation",
    power: "3000W",
    location: "RAAF Base Williamtown, Australia",
  },
  {
    id: "navtex-local",
    frequency: "490 kHz",
    frequencyKhz: 490,
    system: "NAVTEX",
    designation: "National/Local",
    operator: "International",
    band: "MF",
    signalType: "digital",
    description: "NAVTEX national/local language broadcasts. SITOR-B digital mode with navigational warnings.",
    classification: "Navigation",
    notes: "NAVAREA warnings detail military firing exercises, submarine cable ops, closed zones",
  },
  {
    id: "navtex-intl",
    frequency: "518 kHz",
    frequencyKhz: 518,
    system: "NAVTEX",
    designation: "International",
    operator: "International",
    band: "MF",
    signalType: "digital",
    description: "International NAVTEX broadcasts. Intelligence value in NAVAREA warnings.",
    classification: "Navigation",
  },
  {
    id: "ndb-km",
    frequency: "690 kHz",
    frequencyKhz: 690,
    system: "NDB",
    designation: "KM",
    operator: "Russia",
    band: "MF",
    signalType: "beacon",
    description: "NDB at Arkhangelsk Strategic Bomber Base.",
    classification: "Strategic",
    location: "Arkhangelsk, Russia",
  },
  {
    id: "baltic-2166",
    frequency: "2166 kHz",
    frequencyKhz: 2166,
    system: "Russian Navy Fleet Broadcast",
    designation: "Baltic Fleet",
    operator: "Russia",
    band: "MF",
    signalType: "broadcast",
    description: "Baltic Fleet (Kaliningrad) night-time radiogram traffic.",
    classification: "Tactical",
    location: "Kaliningrad, Russia",
  },
  {
    id: "distress-2182",
    frequency: "2182 kHz",
    frequencyKhz: 2182,
    system: "International Distress",
    designation: "Distress/Hailing",
    operator: "International",
    band: "MF",
    signalType: "voice",
    description: "International Distress frequency. Guarded by all naval vessels. Primary inter-navy hailing frequency.",
    classification: "Strategic",
    notes: "Used for 'Dangerous Military Activities' coordination",
  },
  {
    id: "blacksea-2525",
    frequency: "2525 kHz",
    frequencyKhz: 2525,
    system: "Russian Navy Fleet Broadcast",
    designation: "Black Sea Fleet",
    operator: "Russia",
    band: "MF",
    signalType: "broadcast",
    description: "Black Sea Fleet (Sevastopol) regional coverage.",
    classification: "Tactical",
    location: "Sevastopol, Russia",
  },

  // =============================================
  // === HF BAND (3–30 MHz) — The Main Battlefield
  // =============================================

  // --- US HFGCS ---
  {
    id: "hfgcs-4724",
    frequency: "4724.0 kHz",
    frequencyKhz: 4724,
    system: "HFGCS",
    designation: "Mainsail (Night)",
    operator: "USA",
    band: "HF",
    signalType: "voice",
    description: "USAF High Frequency Global Communications System — Night/Short Range. 13 ground stations worldwide.",
    classification: "Strategic",
    notes: "Callsign: MAINSAIL. Carries Skyking EAMs. Ground stations: Andrews, Offutt, Hickam, Yokota, Croughton, Sigonella, Diego Garcia, Lajes, Ascension, Elmendorf, Andersen, Puerto Rico, West Coast.",
    source: "priyom",
    status: "active",
  },
  {
    id: "hfgcs-8992",
    frequency: "8992.0 kHz",
    frequencyKhz: 8992,
    system: "HFGCS",
    designation: "Mainsail (Primary)",
    operator: "USA",
    band: "HF",
    signalType: "voice",
    description: "USAF HFGCS Primary frequency — one of the most active military frequencies in the world.",
    classification: "Strategic",
    notes: "Guarded 24/7. TACAMO & Looking Glass maintain constant guard.",
    source: "priyom",
    status: "active",
  },
  {
    id: "hfgcs-11175",
    frequency: "11175.0 kHz",
    frequencyKhz: 11175,
    system: "HFGCS",
    designation: "Mainsail (Primary Day)",
    operator: "USA",
    band: "HF",
    signalType: "voice",
    description: "USAF HFGCS Primary daytime frequency — carries Emergency Action Messages (EAMs) and Skyking broadcasts.",
    classification: "Strategic",
    notes: "Skyking messages: nuclear execution orders, bomber retargeting, or test drills. Main frequency during daytime.",
    source: "priyom",
    status: "active",
  },
  {
    id: "hfgcs-15016",
    frequency: "15016.0 kHz",
    frequencyKhz: 15016,
    system: "HFGCS",
    designation: "Mainsail (Day)",
    operator: "USA",
    band: "HF",
    signalType: "voice",
    description: "USAF HFGCS Day/Long Range frequency.",
    classification: "Strategic",
    source: "priyom",
    status: "active",
  },

  // --- US HFGCS ALE Frequencies ---
  {
    id: "hfgcs-ale-3137",
    frequency: "3137.0 kHz",
    frequencyKhz: 3137,
    system: "HFGCS ALE",
    designation: "ALE Network",
    operator: "USA",
    band: "HF",
    signalType: "digital",
    description: "HFGCS 2G ALE frequency for text messaging and radio checks. Ground stations emit soundings every 3 hours.",
    classification: "Strategic",
    source: "priyom",
    modulation: "MFSK (2G ALE)",
    status: "active",
  },
  {
    id: "hfgcs-ale-6721",
    frequency: "6721.0 kHz",
    frequencyKhz: 6721,
    system: "HFGCS ALE",
    designation: "ALE Network",
    operator: "USA",
    band: "HF",
    signalType: "digital",
    description: "HFGCS ALE frequency. Station addresses: ADW (Andrews), AED (Elmendorf), CRO (Croughton), GUA (Andersen), etc.",
    classification: "Strategic",
    source: "priyom",
    modulation: "MFSK (2G ALE)",
    status: "active",
  },
  {
    id: "hfgcs-ale-13215",
    frequency: "13215.0 kHz",
    frequencyKhz: 13215,
    system: "HFGCS ALE",
    designation: "ALE Network",
    operator: "USA",
    band: "HF",
    signalType: "digital",
    description: "HFGCS ALE frequency. Aircraft addresses use tail number digits (e.g. NW1 = Boeing E-4 Nightwatch).",
    classification: "Strategic",
    source: "priyom",
    modulation: "MFSK (2G ALE)",
    status: "active",
  },

  // --- US SIPRNet ---
  {
    id: "sipr-3113",
    frequency: "3113.0 kHz",
    frequencyKhz: 3113,
    system: "SIPRNet HF",
    designation: "Secret Network",
    operator: "USA",
    band: "HF",
    signalType: "digital",
    description: "Secret Internet Protocol Router (SIPRNet) HF gateway. Links established via 2G ALE, data via MIL-STD-188-110A.",
    classification: "Strategic",
    source: "priyom",
    status: "active",
  },
  {
    id: "sipr-8968",
    frequency: "8968.0 kHz",
    frequencyKhz: 8968,
    system: "SIPRNet HF",
    designation: "Secret Network",
    operator: "USA",
    band: "HF",
    signalType: "digital",
    description: "SIPRNet HF gateway frequency for classified DoD network access.",
    classification: "Strategic",
    source: "priyom",
    status: "active",
  },
  {
    id: "sipr-17976",
    frequency: "17976.0 kHz",
    frequencyKhz: 17976,
    system: "SIPRNet HF",
    designation: "Secret Network",
    operator: "USA",
    band: "HF",
    signalType: "digital",
    description: "SIPRNet HF gateway frequency.",
    classification: "Strategic",
    source: "priyom",
    status: "active",
  },

  // --- US Military Modems ---
  {
    id: "cv786",
    frequency: "3–30 MHz",
    frequencyKhz: 15000,
    system: "CV-786",
    designation: "Rockwell-Collins MDM-2001",
    operator: "USA",
    band: "HF",
    signalType: "digital",
    description: "Wideband FSK mode in Rockwell-Collins MDM-2001 modems. Also known as TRC-75. Military Radio TeleTYpe mode.",
    classification: "Tactical",
    source: "sigidwiki",
    modulation: "FSK",
    bandwidth: "900 Hz",
    status: "active",
  },
  {
    id: "br6028",
    frequency: "5.75–15.937 MHz",
    frequencyKhz: 10843,
    system: "BR-6028",
    designation: "BARRIE / USA-7",
    operator: "USA",
    band: "HF",
    signalType: "digital",
    description: "VFT (Voice Frequency Telegraph) modem using 7 data channels for frequency and time diversity.",
    classification: "Tactical",
    source: "sigidwiki",
    modulation: "FSK",
    bandwidth: "3.1 kHz",
    status: "active",
  },

  // --- Russian Marker Stations (priyom.org) ---
  {
    id: "buzzer",
    frequency: "4625 kHz",
    frequencyKhz: 4625,
    system: "UVB-76",
    designation: "The Buzzer",
    operator: "Russia",
    band: "HF",
    signalType: "marker",
    description: "The most famous Russian marker station. Buzzing tone ~25 times/minute, interrupted for live voice Monolith messages to the Russian Navy.",
    classification: "Strategic",
    location: "Western Military District",
    notes: "24/7 operation. Callsign NZhTI (formerly ANVF, ZhUOZ, MDZhB, UZB-76).",
    source: "priyom",
    status: "active",
  },
  {
    id: "d-marker",
    frequency: "5292 kHz",
    frequencyKhz: 5292,
    system: "D Marker",
    designation: "D Marker",
    operator: "Russia",
    band: "HF",
    signalType: "marker",
    description: "Russian military marker station serving Moscow & Leningrad Military Districts.",
    classification: "Strategic",
    location: "Moscow/Leningrad MD",
    source: "priyom",
    status: "active",
  },
  {
    id: "t-marker",
    frequency: "4325 kHz",
    frequencyKhz: 4325,
    system: "T Marker",
    designation: "T Marker",
    operator: "Russia",
    band: "HF",
    signalType: "marker",
    description: "Russian military marker station serving Moscow & Leningrad Military Districts.",
    classification: "Strategic",
    location: "Moscow/Leningrad MD",
    source: "priyom",
    status: "active",
  },
  {
    id: "airhorn",
    frequency: "4930 kHz",
    frequencyKhz: 4930,
    system: "The Air Horn",
    designation: "The Air Horn",
    operator: "Russia",
    band: "HF",
    signalType: "marker",
    description: "Russian military commandment network serving the Western Military District. Broadcasts Monolith and MOLNIYA messages.",
    classification: "Strategic",
    location: "Smolensk, Russia",
    source: "priyom",
    status: "unknown",
    notes: "Channel marker replaced by The Goose's marker after Dec 2023.",
  },
  {
    id: "goose-day",
    frequency: "4310 kHz",
    frequencyKhz: 4310,
    system: "The Goose",
    designation: "The Goose (Day)",
    operator: "Russia",
    band: "HF",
    signalType: "marker",
    description: "Russian military commandment network serving the Western Military District. Daytime frequency.",
    classification: "Strategic",
    source: "priyom",
    notes: "Night frequency: 3243 kHz",
    status: "active",
  },
  {
    id: "goose-night",
    frequency: "3243 kHz",
    frequencyKhz: 3243,
    system: "The Goose",
    designation: "The Goose (Night)",
    operator: "Russia",
    band: "HF",
    signalType: "marker",
    description: "Russian military commandment network (night frequency).",
    classification: "Strategic",
    source: "priyom",
    status: "active",
  },
  {
    id: "alarm",
    frequency: "4770 kHz",
    frequencyKhz: 4770,
    system: "The Alarm",
    designation: "The Alarm",
    operator: "Russia",
    band: "HF",
    signalType: "marker",
    description: "Russian military commandment network serving the Western Military District. Primarily test counts, no known actual traffic.",
    classification: "Strategic",
    source: "priyom",
    status: "active",
  },
  {
    id: "pip-day",
    frequency: "5448 kHz",
    frequencyKhz: 5448,
    system: "The Pip",
    designation: "The Pip (Day)",
    operator: "Russia",
    band: "HF",
    signalType: "marker",
    description: "Russian marker station transmitting short beeps ~50/min. Serves Southern Military District. Callsign 8S1Shch, station 'Akacia'.",
    classification: "Strategic",
    notes: "Night frequency: 3756 kHz. Active since ~1986.",
    source: "priyom",
    status: "active",
  },
  {
    id: "pip-night",
    frequency: "3756 kHz",
    frequencyKhz: 3756,
    system: "The Pip",
    designation: "The Pip (Night)",
    operator: "Russia",
    band: "HF",
    signalType: "marker",
    description: "Russian marker station (night frequency). Southern Military District.",
    classification: "Strategic",
    source: "priyom",
    status: "active",
  },
  {
    id: "squeaky-day",
    frequency: "5367 kHz",
    frequencyKhz: 5367,
    system: "The Squeaky Wheel",
    designation: "Squeaky Wheel (Day)",
    operator: "Russia",
    band: "HF",
    signalType: "marker",
    description: "Russian marker station transmitting distinct high-pitched squeaks. Southern Military District.",
    classification: "Strategic",
    notes: "Night frequency: 3363.5 kHz",
    source: "priyom",
    status: "active",
  },
  {
    id: "vega",
    frequency: "5372 kHz",
    frequencyKhz: 5372,
    system: "Vega-33",
    designation: "Vega",
    operator: "Russia",
    band: "HF",
    signalType: "marker",
    description: "Russian military marker station serving the Southern Military District.",
    classification: "Strategic",
    source: "priyom",
    status: "active",
  },
  {
    id: "baron78-day",
    frequency: "4940 kHz",
    frequencyKhz: 4940,
    system: "Baron-78",
    designation: "Baron78 (Day)",
    operator: "Russia",
    band: "HF",
    signalType: "marker",
    description: "Russian military marker station. Southern Military District. Night: 3850 kHz.",
    classification: "Strategic",
    source: "priyom",
    status: "active",
  },
  {
    id: "berkut24",
    frequency: "5210 kHz",
    frequencyKhz: 5210,
    system: "Berkut24",
    designation: "Berkut24 (Day)",
    operator: "Russia",
    band: "HF",
    signalType: "marker",
    description: "Russian military marker station. Southern Military District. Night: 3870 kHz.",
    classification: "Strategic",
    source: "priyom",
    status: "active",
  },
  {
    id: "katok65",
    frequency: "4224 kHz",
    frequencyKhz: 4224,
    system: "Katok-65",
    designation: "Katok65 (Day)",
    operator: "Russia",
    band: "HF",
    signalType: "marker",
    description: "Russian military marker station. Moscow/Leningrad MD. Night: 3218.5 kHz.",
    classification: "Strategic",
    source: "priyom",
    status: "active",
  },
  {
    id: "zaliv52",
    frequency: "4110 kHz",
    frequencyKhz: 4110,
    system: "Zaliv52",
    designation: "Zaliv52",
    operator: "Russia",
    band: "HF",
    signalType: "marker",
    description: "Military station broadcasting Monolith and MOLNIYA 5X messages. No channel marker.",
    classification: "Strategic",
    location: "Moscow, Russia (speculated)",
    source: "priyom",
    status: "active",
  },

  // --- Russian Navy Beacons ---
  {
    id: "slb-3594",
    frequency: "3594 kHz cluster",
    frequencyKhz: 3594,
    system: "Single Letter Beacons",
    designation: "C/S/D/P/F",
    operator: "Russia",
    band: "HF",
    signalType: "beacon",
    description: "Russian Navy propagation beacons: C (Moscow), S (Severomorsk), D (Sevastopol), P (Kaliningrad), F (Vladivostok).",
    classification: "Tactical",
    notes: "Clustered in 100 Hz increments around center frequency",
  },
  {
    id: "slb-7508",
    frequency: "7508 kHz cluster",
    frequencyKhz: 7508,
    system: "Single Letter Beacons",
    designation: "C/S/D/P/F",
    operator: "Russia",
    band: "HF",
    signalType: "beacon",
    description: "Russian Navy Single Letter Beacon cluster for propagation analysis.",
    classification: "Tactical",
  },
  {
    id: "slb-10871",
    frequency: "10871 kHz cluster",
    frequencyKhz: 10871,
    system: "Single Letter Beacons",
    designation: "C/S/D/P/F",
    operator: "Russia",
    band: "HF",
    signalType: "beacon",
    description: "Russian Navy Single Letter Beacon cluster.",
    classification: "Tactical",
  },

  // --- Russian Digital Modems (sigidwiki CIS family) ---
  {
    id: "akkord",
    frequency: "7.051 MHz",
    frequencyKhz: 7051,
    system: "AKKORD-SS-PD",
    designation: "Akkord-165",
    operator: "Russia",
    band: "HF",
    signalType: "datalink",
    description: "Russian tactical datalink used during the invasion of Ukraine. Akkord-165 is the most recent version of the Akkord protocol family.",
    classification: "Tactical",
    source: "sigidwiki",
    modulation: "MSK",
    bandwidth: "1.2 kHz",
    status: "active",
  },
  {
    id: "cis-mfsk68",
    frequency: "7.659–18.28 MHz",
    frequencyKhz: 12970,
    system: "CIS MFSK-68 (Perelivt)",
    designation: "Russian Diplomatic",
    operator: "Russia",
    band: "HF",
    signalType: "digital",
    description: "68-tone MFSK modem with 9000 Bd 8-PSK inserts spanning 10 kHz. Used by Russian diplomatic services. Unofficial name 'Perelivt'.",
    classification: "Strategic",
    source: "sigidwiki",
    modulation: "MFSK, PSK",
    bandwidth: "10 kHz",
    status: "active",
  },
  {
    id: "cis-ofdm-hdr",
    frequency: "3–30 MHz",
    frequencyKhz: 16500,
    system: "CIS OFDM HDR Modem",
    designation: "CIS-45/60/93",
    operator: "Russia",
    band: "HF",
    signalType: "digital",
    description: "Russian OFDM High Data Rate Modem with three modes: CIS-45, CIS-60, CIS-93 (number of OFDM tones).",
    classification: "Tactical",
    source: "sigidwiki",
    modulation: "PSK, OFDM",
    bandwidth: "2.8–3 kHz",
    status: "active",
  },
  {
    id: "cis1200-mahovik",
    frequency: "3–30 MHz",
    frequencyKhz: 16500,
    system: "CIS-1200 (Mahovik)",
    designation: "T-230-1A Flywheel",
    operator: "Russia",
    band: "HF",
    signalType: "digital",
    description: "PSK mode transmitting both voice and data from Russian T-230-1A transceiver. 'Mahovik' means 'Flywheel' in Russian.",
    classification: "Tactical",
    source: "sigidwiki",
    modulation: "SDPSK, BPSK",
    bandwidth: "2.5 kHz",
    status: "active",
  },
  {
    id: "yachta",
    frequency: "3–30 MHz",
    frequencyKhz: 16500,
    system: "Yachta T-219",
    designation: "Voice Scrambler",
    operator: "Russia",
    band: "HF",
    signalType: "scrambler",
    description: "Analogue voice scrambler. Unique: FSK sync signal in the middle with scrambled voice split above and below.",
    classification: "Tactical",
    source: "sigidwiki",
    modulation: "FSK",
    bandwidth: "2.7 kHz",
    status: "active",
  },

  // --- Russian RDL Network ---
  {
    id: "rdl-3244",
    frequency: "3244 kHz",
    frequencyKhz: 3244,
    system: "RDL Monolith Network",
    designation: "Strategic Broadcast",
    operator: "Russia",
    band: "HF",
    signalType: "digital",
    description: "Russian strategic broadcast system carrying Monolith command messages.",
    classification: "Strategic",
    notes: "Uses T-600 (50 Baud FSK) and AT-3104 (multi-tone PSK)",
  },
  {
    id: "rdl-8136",
    frequency: "8136 kHz",
    frequencyKhz: 8136,
    system: "RDL Monolith Network",
    designation: "Strategic Broadcast",
    operator: "Russia",
    band: "HF",
    signalType: "digital",
    description: "RDL network frequency for strategic command messages.",
    classification: "Strategic",
  },

  // --- OTH Radars ---
  {
    id: "kontayner",
    frequency: "6.1–32 MHz",
    frequencyKhz: 19050,
    system: "29B6 Kontayner",
    designation: "OTH Radar",
    operator: "Russia",
    band: "HF",
    signalType: "radar",
    description: "Russian over-the-horizon radar using 150 antenna masts. Detects aircraft and missiles at very long ranges. Very active in Europe.",
    classification: "Strategic",
    source: "sigidwiki",
    modulation: "FMOP, Pulsed",
    bandwidth: "3.5–28 kHz",
    status: "active",
  },
  {
    id: "podsolnukh",
    frequency: "3.5–8 MHz",
    frequencyKhz: 5750,
    system: "Podsolnukh (Sunflower)",
    designation: "OTH Radar",
    operator: "Russia",
    band: "HF",
    signalType: "radar",
    description: "Russian coastal over-the-horizon radar also known as 'Sunflower'.",
    classification: "Tactical",
    source: "sigidwiki",
    modulation: "FMOP",
    bandwidth: "50 kHz",
    status: "active",
  },
  {
    id: "oth-sw",
    frequency: "6–30 MHz",
    frequencyKhz: 18000,
    system: "OTH-SW",
    designation: "Chinese OTH Radar",
    operator: "China",
    band: "HF",
    signalType: "radar",
    description: "Chinese over-the-horizon radar operating with pulse repetition frequencies of 43 Hz and 86 Hz.",
    classification: "Strategic",
    source: "sigidwiki",
    modulation: "FMCW",
    bandwidth: "40–80 kHz",
    status: "active",
  },
  {
    id: "foghorn",
    frequency: "6–29 MHz",
    frequencyKhz: 17500,
    system: "Chinese Foghorn",
    designation: "OTH Radar",
    operator: "China",
    band: "HF",
    signalType: "radar",
    description: "Chinese over-the-horizon radar nicknamed 'Foghorn' by amateur radio operators.",
    classification: "Strategic",
    source: "sigidwiki",
    modulation: "FMCW",
    bandwidth: "10 kHz",
    status: "active",
  },
  {
    id: "ghadir",
    frequency: "28–29.7 MHz",
    frequencyKhz: 28850,
    system: "Ghadir OTH Radar",
    designation: "Sepehr System",
    operator: "Iran",
    band: "HF",
    signalType: "radar",
    description: "Iranian over-the-horizon radar, part of Iran's Sepehr Phased Radar System.",
    classification: "Strategic",
    location: "Iran",
    source: "sigidwiki",
    modulation: "Pulse",
    bandwidth: "60 kHz – 1 MHz",
    status: "active",
  },
  {
    id: "pluto2",
    frequency: "8–38 MHz",
    frequencyKhz: 23000,
    system: "PLUTO II",
    designation: "OTH Radar",
    operator: "UK",
    band: "HF",
    signalType: "radar",
    description: "Over The Horizon Radar near RAF Akrotiri in Cyprus. Very active in Europe.",
    classification: "Strategic",
    location: "RAF Akrotiri, Cyprus",
    source: "sigidwiki",
    modulation: "FMCW",
    bandwidth: "20–40 kHz",
    status: "active",
  },

  // --- NATO Data Links ---
  {
    id: "link11",
    frequency: "2–30 MHz",
    frequencyKhz: 16000,
    system: "Link-11 (TADIL-A)",
    designation: "STANAG 5511",
    operator: "NATO",
    band: "HF",
    signalType: "datalink",
    description: "NATO Tactical Data Link for Maritime Tactical Data Exchange. Also known as ALLIGATOR, MIL-STD-6011.",
    classification: "Tactical",
    source: "sigidwiki",
    modulation: "PSK",
    bandwidth: "2.5–6 kHz",
    status: "active",
  },
  {
    id: "stanag4481",
    frequency: "2.815–18.016 MHz",
    frequencyKhz: 10416,
    system: "STANAG 4481 (CRATT)",
    designation: "NATO Shore-to-Ship",
    operator: "NATO",
    band: "HF",
    signalType: "digital",
    description: "NATO standard for naval HF shore-to-ship broadcast system. Also known as Link-4 and NATO-75.",
    classification: "Tactical",
    source: "sigidwiki",
    modulation: "FSK, PSK",
    bandwidth: "1.5–2.75 kHz",
    status: "active",
  },

  // --- French Military ---
  {
    id: "arqe",
    frequency: "3–30 MHz",
    frequencyKhz: 16500,
    system: "ARQ-E (E3)",
    designation: "French Military ARQ",
    operator: "France",
    band: "HF",
    signalType: "digital",
    description: "Synchronous full-duplex ARQ system (ARQ-1000 Duplex). Mainly used by French Military Forces. Stations commonly idle for hours.",
    classification: "Tactical",
    source: "sigidwiki",
    modulation: "FSK",
    bandwidth: "85–850 Hz",
    status: "active",
  },
  {
    id: "thales3000",
    frequency: "1.5–30 MHz",
    frequencyKhz: 15750,
    system: "Thales Système 3000",
    designation: "French HF Modem",
    operator: "France",
    band: "HF",
    signalType: "digital",
    description: "Multi-mode HF modem with unique preamble. Supports PSK, MFSK, voice scrambling, and Skyhopper frequency hopping.",
    classification: "Tactical",
    source: "sigidwiki",
    modulation: "PSK, MFSK",
    bandwidth: "2–3 kHz",
    status: "active",
  },
  {
    id: "salamandre",
    frequency: "3–30 MHz",
    frequencyKhz: 16500,
    system: "Thales SALAMANDRE (HFXL)",
    designation: "Wideband HF",
    operator: "France",
    band: "HF",
    signalType: "digital",
    description: "Uses up to 16 separate HF channels for high datarate military communications on modified STANAG-4539 platform.",
    classification: "Tactical",
    source: "sigidwiki",
    modulation: "PSK",
    bandwidth: "150 kHz aggregate",
    status: "active",
  },

  // --- Israeli Military ---
  {
    id: "israeli-navy-hybrid",
    frequency: "3–30 MHz",
    frequencyKhz: 16500,
    system: "Israeli Navy Hybrid Modem",
    designation: "188-110 MOD",
    operator: "Israel",
    band: "HF",
    signalType: "digital",
    description: "Based on MIL-STD-188-110 Serial with characteristic 4/6 tone and 18 QPSK preamble. Used by Israeli Navy 4XZ station from Haifa.",
    classification: "Tactical",
    location: "Haifa, Israel",
    source: "sigidwiki",
    modulation: "PSK",
    bandwidth: "2.75 kHz",
    status: "active",
  },
  {
    id: "israeli-vft",
    frequency: "3–30 MHz",
    frequencyKhz: 16500,
    system: "Israeli VFT",
    designation: "Government/Military",
    operator: "Israel",
    band: "HF",
    signalType: "digital",
    description: "Israeli VFT transmission used by Israeli government or military.",
    classification: "Tactical",
    source: "sigidwiki",
    modulation: "FSK, PSK",
    bandwidth: "3.1 kHz",
    status: "active",
  },
  {
    id: "iaf-5123",
    frequency: "5123 kHz",
    frequencyKhz: 5123,
    system: "IAF HF Network",
    designation: "Set 1 (USB)",
    operator: "Israel",
    band: "HF",
    signalType: "voice",
    description: "Israeli Air Force HF network for long-range strike coordination.",
    classification: "Tactical",
  },

  // --- Chinese Military ---
  {
    id: "pla-m89-3197",
    frequency: "3197 kHz",
    frequencyKhz: 3197,
    system: "PLA Rocket Force M89",
    designation: "M89 (Morse CW)",
    operator: "China",
    band: "HF",
    signalType: "numbers",
    description: "PLA Rocket Force massive CW network — coded messages to missile brigades.",
    classification: "Strategic",
    notes: "Highly redundant C2 structure",
  },
  {
    id: "pla-v26-6719",
    frequency: "6719 kHz",
    frequencyKhz: 6719,
    system: "PLA V26 Voice",
    designation: "V26 (Numbers Station)",
    operator: "China",
    band: "HF",
    signalType: "numbers",
    description: "Female voice reading numbers with 4+4 digit callsigns. Operates parallel with M89.",
    classification: "Strategic",
  },
  {
    id: "chinese-30tone",
    frequency: "3.618–18.656 MHz",
    frequencyKhz: 11137,
    system: "Chinese 30-tone OFDM",
    designation: "Military OFDM",
    operator: "China",
    band: "HF",
    signalType: "digital",
    description: "30-tone OFDM data mode probably used by Chinese military or other agencies.",
    classification: "Tactical",
    source: "sigidwiki",
    modulation: "QPSK, BPSK, OFDM",
    bandwidth: "3 kHz",
    status: "active",
  },
  {
    id: "chinese-64mfsk",
    frequency: "3.673–16.989 MHz",
    frequencyKhz: 10331,
    system: "Chinese-64 MFSK",
    designation: "Chinese Modem",
    operator: "China",
    band: "HF",
    signalType: "digital",
    description: "Chinese 64-tone MFSK modem.",
    classification: "Tactical",
    source: "sigidwiki",
    modulation: "MFSK",
    bandwidth: "2.5 kHz",
    status: "active",
  },
  {
    id: "prc16",
    frequency: "14.3 MHz",
    frequencyKhz: 14300,
    system: "PRC-16",
    designation: "Chinese PSK Datalink",
    operator: "China",
    band: "HF",
    signalType: "datalink",
    description: "Chinese-sourced PSK data link traced to Shanghai. Suspected user: Chinese Military.",
    classification: "Tactical",
    location: "Shanghai, China",
    source: "sigidwiki",
    modulation: "PSK, OFDM",
    bandwidth: "2.2 kHz",
    status: "active",
  },
  {
    id: "pla-ale-9042",
    frequency: "9042 kHz",
    frequencyKhz: 9042,
    system: "PLA 2G ALE",
    designation: "PLAAF ALE",
    operator: "China",
    band: "HF",
    signalType: "digital",
    description: "PLA Air Force 2G ALE network. Stations scan frequencies in descending order.",
    classification: "Tactical",
    notes: "Numeric station IDs (100-126, 922-928)",
  },

  // --- Iranian Military ---
  {
    id: "iranian-navy-qpsk",
    frequency: "8.046–17.382 MHz",
    frequencyKhz: 12714,
    system: "Iranian Navy QPSK",
    designation: "Navy Modem V2",
    operator: "Iran",
    band: "HF",
    signalType: "digital",
    description: "QPSK mode used by Iranian Navy. V2 (2015) supports 468, 936, and 1872 Bd speeds.",
    classification: "Tactical",
    source: "sigidwiki",
    modulation: "QPSK",
    bandwidth: "300 Hz – 2.85 kHz",
    status: "active",
  },

  // --- Japanese Military ---
  {
    id: "jsdf-3195",
    frequency: "3195 kHz",
    frequencyKhz: 3195,
    system: "JSDF HF Net",
    designation: "JJT88 (Tokyo)",
    operator: "Japan",
    band: "HF",
    signalType: "voice",
    description: "Japan Self-Defense Forces HF aerial coordination net.",
    classification: "Tactical",
    notes: "Net control JJT88 Tokyo, outstations like JJS21 Misawa",
  },
  {
    id: "japan-8ch-fsk",
    frequency: "4.295–16.554 MHz",
    frequencyKhz: 10425,
    system: "Japan Military 8-Ch FSK",
    designation: "Navy Data",
    operator: "Japan",
    band: "HF",
    signalType: "digital",
    description: "8-channel FSK data signal thought to originate from Japanese Military/Navy.",
    classification: "Tactical",
    source: "sigidwiki",
    modulation: "FSK",
    bandwidth: "2.4 kHz",
    status: "active",
  },

  // --- Australian Military ---
  {
    id: "mhfcs",
    frequency: "2.01–27.478 MHz",
    frequencyKhz: 14744,
    system: "MHFCS",
    designation: "ADF HFCS",
    operator: "Australia",
    band: "HF",
    signalType: "digital",
    description: "Modernised High Frequency Communications System for Australian Department of Defence. Also known as AUS MIL ISB Modem.",
    classification: "Tactical",
    source: "sigidwiki",
    modulation: "FSK",
    bandwidth: "400–750 Hz",
    status: "active",
  },

  // --- Number Stations ---
  {
    id: "f07",
    frequency: "5–17.5 MHz",
    frequencyKhz: 11250,
    system: "F07 Number Station",
    designation: "Russian Digital",
    operator: "Russia",
    band: "HF",
    signalType: "numbers",
    description: "Russian digital number station using multiple modulation types: MFSK, BPSK, and FSK.",
    classification: "Strategic",
    source: "sigidwiki",
    modulation: "MFSK, BPSK, FSK",
    bandwidth: "4 kHz",
    status: "active",
  },
  {
    id: "one-beep",
    frequency: "4.5–6.429 MHz",
    frequencyKhz: 5465,
    system: "One Beep, Two Beeps",
    designation: "Norwegian Navy",
    operator: "NATO",
    band: "HF",
    signalType: "marker",
    description: "Signal emitted by the Norwegian Navy communications center in Bodø.",
    classification: "Tactical",
    location: "Bodø, Norway",
    source: "sigidwiki",
    status: "active",
  },

  // --- Voice Scramblers ---
  {
    id: "hc265",
    frequency: "3–30 MHz",
    frequencyKhz: 16500,
    system: "HC-265 Voice Scrambler",
    designation: "Hagelin Crypto",
    operator: "International",
    band: "HF",
    signalType: "scrambler",
    description: "Voice Scrambling mode developed by Hagelin Crypto for their HC-265 CRYPTOCOM secure voice unit.",
    classification: "Tactical",
    source: "sigidwiki",
    modulation: "FSK",
    bandwidth: "2.25–3 kHz",
    status: "active",
  },

  // --- Other Notable Systems ---
  {
    id: "panther-h",
    frequency: "1.5–30 MHz",
    frequencyKhz: 15750,
    system: "Panther-H (Thales)",
    designation: "Freq Hopping",
    operator: "International",
    band: "HF",
    signalType: "digital",
    description: "Intelligent frequency hopping transceiver by Racal (now Thales). 8-burst SOC sync procedure. Used in Panther-2000H radios.",
    classification: "Tactical",
    source: "sigidwiki",
    modulation: "PSK",
    bandwidth: "3 kHz",
    status: "active",
  },
  {
    id: "gm2100",
    frequency: "3–30 MHz",
    frequencyKhz: 16500,
    system: "GM2100 (Rohde & Schwarz)",
    designation: "R&S HF Modem",
    operator: "International",
    band: "HF",
    signalType: "digital",
    description: "Proprietary HF Data Signal Protocol for the Rohde & Schwarz HF Modem GM2100.",
    classification: "Tactical",
    location: "Europe",
    source: "sigidwiki",
    modulation: "PSK",
    bandwidth: "3 kHz",
    status: "active",
  },
  {
    id: "saab-mhf50",
    frequency: "4.245–12.982 MHz",
    frequencyKhz: 8614,
    system: "Saab Grintek MHF-50",
    designation: "MFSK Modem",
    operator: "International",
    band: "HF",
    signalType: "digital",
    description: "MFSK modem by Saab Grintek Technologies (South Africa). Uses RTTY, 2-FSK, and 33-MFSK.",
    classification: "Tactical",
    location: "South Africa",
    source: "sigidwiki",
    modulation: "MFSK, FSK",
    bandwidth: "2.2 kHz",
    status: "active",
  },
  {
    id: "qmac",
    frequency: "3–30 MHz",
    frequencyKhz: 16500,
    system: "Q-MAC HF Modem",
    designation: "Barrett Comms",
    operator: "Australia",
    band: "HF",
    signalType: "digital",
    description: "Military modem by Q-MAC (acquired by Barrett Communications). OFDM with BPSK sync channel in signal gap.",
    classification: "Tactical",
    source: "sigidwiki",
    modulation: "PSK, OFDM, PSK8",
    bandwidth: "2 kHz",
    status: "active",
  },
  {
    id: "skyofdm",
    frequency: "3–30 MHz",
    frequencyKhz: 16500,
    system: "SkyOFDM",
    designation: "SkySweep Technologies",
    operator: "International",
    band: "HF",
    signalType: "digital",
    description: "Data transmission mode developed by SkySweep Technologies in Finland. Probably used by Finnish MFA.",
    classification: "Tactical",
    location: "Finland",
    source: "sigidwiki",
    modulation: "PSK, OFDM",
    bandwidth: "2–2.4 kHz",
    status: "active",
  },
  {
    id: "marconi-25tone",
    frequency: "3–30 MHz",
    frequencyKhz: 16500,
    system: "Marconi Selenia 25-Tone",
    designation: "Military Modem",
    operator: "NATO",
    band: "HF",
    signalType: "digital",
    description: "25-tone OFDM PSK modem by Marconi Selenia (now Finmeccanica). Supports ECCM capability at 2400 bps. Employed by Turkey.",
    classification: "Tactical",
    source: "sigidwiki",
    modulation: "PSK, OFDM",
    bandwidth: "1.6 kHz",
    status: "active",
  },

  // --- Aeronautical Off Route Sub-Bands (radioreference.com) ---
  {
    id: "aero-offroute-4700",
    frequency: "4700–4750 kHz",
    frequencyKhz: 4725,
    system: "Aero Off Route",
    designation: "Military Aircraft",
    operator: "International",
    band: "HF",
    signalType: "voice",
    description: "Aeronautical Off Route Sub-Band designated for military aircraft usage with 3 kHz channel spacing.",
    classification: "Tactical",
    source: "radioreference",
    status: "active",
  },
  {
    id: "aero-offroute-6685",
    frequency: "6685–6765 kHz",
    frequencyKhz: 6725,
    system: "Aero Off Route",
    designation: "Military Aircraft",
    operator: "International",
    band: "HF",
    signalType: "voice",
    description: "Aeronautical Off Route Sub-Band for military HF communications.",
    classification: "Tactical",
    source: "radioreference",
    status: "active",
  },
  {
    id: "aero-offroute-8965",
    frequency: "8965–9040 kHz",
    frequencyKhz: 9003,
    system: "Aero Off Route",
    designation: "Military Aircraft",
    operator: "International",
    band: "HF",
    signalType: "voice",
    description: "Aeronautical Off Route Sub-Band for military HF communications.",
    classification: "Tactical",
    source: "radioreference",
    status: "active",
  },

  // =============================================
  // === VHF BAND (30–300 MHz) — Tactical
  // =============================================
  {
    id: "sincgars",
    frequency: "30.000–87.975 MHz",
    frequencyKhz: 59000,
    system: "SINCGARS",
    designation: "NATO Combat Net Radio",
    operator: "NATO",
    band: "VHF",
    signalType: "voice",
    description: "Single Channel Ground and Airborne Radio System. 2320 channels at 25 kHz spacing. FM voice or frequency hopping.",
    classification: "Tactical",
    notes: "FH mode hops ~100 times/sec — appears as 'popcorn' noise on waterfall",
    status: "active",
  },
  {
    id: "nato-armor",
    frequency: "41.00–47.00 MHz",
    frequencyKhz: 44000,
    system: "NATO Harmonized",
    designation: "Primary Armor Band",
    operator: "NATO",
    band: "VHF",
    signalType: "voice",
    description: "Primary tank communications band. Wavelength penetrates forests and urban clutter.",
    classification: "Tactical",
    notes: "The 'sweet spot' for armor communications",
    status: "active",
  },
  {
    id: "nato-airground",
    frequency: "73.30–74.10 MHz",
    frequencyKhz: 73700,
    system: "NATO Harmonized",
    designation: "Air-Ground Coordination",
    operator: "NATO",
    band: "VHF",
    signalType: "voice",
    description: "NATO Air-Ground coordination band.",
    classification: "Tactical",
    status: "active",
  },
  {
    id: "russia-lowvhf",
    frequency: "30–50 MHz",
    frequencyKhz: 40000,
    system: "Russian Tactical",
    designation: "R-123 / R-173 Magnolia",
    operator: "Russia",
    band: "VHF",
    signalType: "voice",
    description: "Primary band for Russian armor and mechanized infantry. 'Over the hill' communication for ground maneuver.",
    classification: "Tactical",
    notes: "Soviet-legacy R-123 and R-173 radios",
    status: "active",
  },
  {
    id: "17067bps-fsk",
    frequency: "30–88 MHz",
    frequencyKhz: 59000,
    system: "17067bps FSK",
    designation: "Unknown Military",
    operator: "International",
    band: "VHF",
    signalType: "digital",
    description: "Unknown military-use signal reminiscent of SECURENET CVSD voice.",
    classification: "Tactical",
    source: "sigidwiki",
    modulation: "FSK",
    bandwidth: "25 kHz",
    status: "unknown",
  },
  {
    id: "monaco-fire",
    frequency: "138.95–139.675 MHz",
    frequencyKhz: 139313,
    system: "Monaco MAAP Fire Alarm",
    designation: "DoD Fire Alarm",
    operator: "USA",
    band: "VHF",
    signalType: "digital",
    description: "Fire alarm control panel built for the US Department of Defense.",
    classification: "Tactical",
    source: "sigidwiki",
    modulation: "FSK",
    bandwidth: "15 kHz",
    status: "active",
  },

  // =============================================
  // === UHF BAND (300 MHz – 3 GHz) — Satellite & Radar
  // =============================================
  {
    id: "voronezh",
    frequency: "150–440 MHz",
    frequencyKhz: 295000,
    system: "77Ya6 Voronezh",
    designation: "ABM Radar",
    operator: "Russia",
    band: "UHF",
    signalType: "radar",
    description: "Russian radar family capable of aircraft and ballistic missile monitoring. Multiple installations across Russia.",
    classification: "Strategic",
    source: "sigidwiki",
    modulation: "FMCW",
    bandwidth: "2 MHz",
    status: "active",
  },
  {
    id: "link11-uhf",
    frequency: "225–399.975 MHz",
    frequencyKhz: 312488,
    system: "Link-11 (UHF)",
    designation: "TADIL-A UHF",
    operator: "NATO",
    band: "UHF",
    signalType: "datalink",
    description: "UHF band variant of Link-11 transmitted on FM carrier. Baseband identical to HF Link-11 waveform.",
    classification: "Tactical",
    source: "sigidwiki",
    modulation: "PSK (FM carrier)",
    bandwidth: "30 kHz",
    status: "active",
  },
  {
    id: "milstar",
    frequency: "243.785–243.822 MHz",
    frequencyKhz: 243804,
    system: "Milstar",
    designation: "FHSS Satellite",
    operator: "USA",
    band: "UHF",
    signalType: "digital",
    description: "UHF FHSS Downlink of Milstar — US joint military satellite communications providing secure, jam-resistant worldwide comms. Nicknamed 'Waterdroplets'.",
    classification: "Strategic",
    source: "sigidwiki",
    modulation: "FHSS",
    bandwidth: "50 kHz",
    status: "active",
  },
  {
    id: "tacan",
    frequency: "960–1213 MHz",
    frequencyKhz: 1086500,
    system: "TACAN",
    designation: "Tactical Air Navigation",
    operator: "International",
    band: "UHF",
    signalType: "navigation",
    description: "Radio navigation measuring slant range between aircraft and ground stations by timing propagation delay.",
    classification: "Navigation",
    source: "sigidwiki",
    modulation: "PAM",
    status: "active",
  },
  {
    id: "cobra-dane",
    frequency: "1215–1400 MHz",
    frequencyKhz: 1307500,
    system: "Cobra Dane (AN/FPS-108)",
    designation: "PESA Radar",
    operator: "USA",
    band: "UHF",
    signalType: "radar",
    description: "PESA phased array radar at Eareckson Air Station, Shemya, Alaska. Operated by Raytheon for US Space Force.",
    classification: "Strategic",
    location: "Shemya, Alaska",
    source: "sigidwiki",
    status: "active",
  },
  {
    id: "coriolis",
    frequency: "2221.5 MHz",
    frequencyKhz: 2221500,
    system: "CORIOLIS Satellite",
    designation: "Tactical Direct Broadcast",
    operator: "USA",
    band: "UHF",
    signalType: "digital",
    description: "Direct Broadcast digital signal from CORIOLIS satellite carrying WindSat instrument data.",
    classification: "Tactical",
    source: "sigidwiki",
    modulation: "BPSK",
    bandwidth: "2 MHz",
    status: "active",
  },

  // --- Inactive/Historical (for reference) ---
  {
    id: "duga3",
    frequency: "7–19 MHz",
    frequencyKhz: 13000,
    system: "Duga-3",
    designation: "Russian Woodpecker",
    operator: "Russia",
    band: "HF",
    signalType: "radar",
    description: "Soviet over-the-horizon radar (1976-1989). Extremely powerful (>10 MW). Known as the 'Russian Woodpecker' for its 10 Hz tapping noise.",
    classification: "Strategic",
    location: "Chernobyl, Ukraine / Eastern Siberia",
    source: "sigidwiki",
    bandwidth: "20 kHz – 800 kHz",
    status: "inactive",
    notes: "Two installations: near Chernobyl and in eastern Siberia. Shut down December 1989.",
  },
  {
    id: "piccolo",
    frequency: "3–30 MHz",
    frequencyKhz: 16500,
    system: "Piccolo",
    designation: "UK FCO MFSK",
    operator: "UK",
    band: "HF",
    signalType: "digital",
    description: "MFSK system developed by UK Foreign and Commonwealth Office for embassy and military communications worldwide. No longer used.",
    classification: "Tactical",
    source: "sigidwiki",
    modulation: "MFSK",
    bandwidth: "180–300 Hz",
    status: "inactive",
  },
];

// Helper: get all unique operators
export const ALL_OPERATORS: Operator[] = ["USA", "Russia", "China", "NATO", "Israel", "Japan", "Australia", "Canada", "France", "UK", "Iran", "Sweden", "International"];

// Helper: get all unique signal types
export const ALL_SIGNAL_TYPES: SignalType[] = ["voice", "digital", "beacon", "navigation", "radar", "marker", "numbers", "broadcast", "scrambler", "datalink"];

export const SIGNAL_TYPE_COLORS: Record<SignalType, string> = {
  voice: "#22c55e",
  digital: "#3b82f6",
  beacon: "#f59e0b",
  navigation: "#06b6d4",
  radar: "#ef4444",
  marker: "#a855f7",
  numbers: "#ec4899",
  broadcast: "#10b981",
  scrambler: "#f97316",
  datalink: "#6366f1",
};

export const SIGNAL_TYPE_LABELS: Record<SignalType, string> = {
  voice: "Voice",
  digital: "Digital",
  beacon: "Beacon",
  navigation: "Nav",
  radar: "Radar",
  marker: "Marker",
  numbers: "Numbers",
  broadcast: "Broadcast",
  scrambler: "Scrambler",
  datalink: "Datalink",
};

// Helper: get all unique classifications
export const ALL_CLASSIFICATIONS = ["Strategic", "Tactical", "Navigation"] as const;

// Operator colors for UI
export const OPERATOR_COLORS: Record<Operator, string> = {
  USA: "#3b82f6",
  Russia: "#ef4444",
  China: "#f59e0b",
  NATO: "#06b6d4",
  Israel: "#8b5cf6",
  Japan: "#ec4899",
  Australia: "#22c55e",
  Canada: "#f97316",
  France: "#6366f1",
  UK: "#a855f7",
  Iran: "#84cc16",
  Sweden: "#14b8a6",
  International: "#94a3b8",
};

// Operator flag labels for compact display
export const OPERATOR_FLAGS: Record<Operator, string> = {
  USA: "US",
  Russia: "RU",
  China: "CN",
  NATO: "NATO",
  Israel: "IL",
  Japan: "JP",
  Australia: "AU",
  Canada: "CA",
  France: "FR",
  UK: "UK",
  Iran: "IR",
  Sweden: "SE",
  International: "INTL",
};
