/**
 * militaryRfData.ts — Military RF Communication Bands Database
 * Source: "Global Military Spectrum Dominance: Operational Analysis of RF Command and Control (100 kHz – 70 MHz)"
 * 
 * Structured data for the Military RF Intelligence reference panel.
 */

export type BandCategory = "LF" | "MF" | "HF" | "VHF";
export type Operator = "USA" | "Russia" | "China" | "NATO" | "Israel" | "Japan" | "Australia" | "Canada" | "International";
export type SignalType = "voice" | "digital" | "beacon" | "navigation" | "radar" | "marker" | "numbers" | "broadcast";

export interface MilitaryFrequency {
  id: string;
  frequency: string;        // e.g. "8992.0 kHz" or "30-88 MHz"
  frequencyKhz: number;     // numeric for sorting (center freq in kHz)
  system: string;            // e.g. "HFGCS", "UVB-76", "SINCGARS"
  designation: string;       // e.g. "Mainsail", "The Buzzer"
  operator: Operator;
  band: BandCategory;
  signalType: SignalType;
  description: string;
  classification: string;    // e.g. "Strategic", "Tactical", "Navigation"
  power?: string;            // e.g. "400W", "Megawatt"
  location?: string;
  notes?: string;
}

export interface BandSection {
  id: BandCategory;
  label: string;
  range: string;
  description: string;
  color: string;
  propagation: string;
}

export interface WaveformInfo {
  id: string;
  name: string;
  standard: string;
  description: string;
  bandwidth: string;
  users: string;
  visualId: string;
}

export const BAND_SECTIONS: BandSection[] = [
  {
    id: "LF",
    label: "LF",
    range: "100 kHz – 300 kHz",
    description: "Subterranean & Strategic Command Layer",
    color: "#f59e0b",
    propagation: "Ground Wave — signals hug Earth's curvature for maritime/coastal reach",
  },
  {
    id: "MF",
    label: "MF",
    range: "300 kHz – 3 MHz",
    description: "Medium Frequency Naval Bridge",
    color: "#06b6d4",
    propagation: "Ground Wave over seawater — reliable fleet coordination over hundreds of miles",
  },
  {
    id: "HF",
    label: "HF",
    range: "3 MHz – 30 MHz",
    description: "Strategic High Frequency Global Battlefield",
    color: "#ef4444",
    propagation: "Sky Wave — ionospheric reflection enables intercontinental range without satellites",
  },
  {
    id: "VHF",
    label: "Low VHF",
    range: "30 MHz – 70 MHz",
    description: "Tactical Edge",
    color: "#22c55e",
    propagation: "Line-of-Sight / Diffraction — penetrates foliage, preferred for armor & infantry",
  },
];

export const WAVEFORMS: WaveformInfo[] = [
  {
    id: "stanag4285",
    name: "STANAG 4285",
    standard: "NATO HF Modem",
    description: "Phase Shift Keying (PSK8) on 1800 Hz subcarrier. Standard NATO HF data waveform.",
    bandwidth: "3 kHz (600–3000 Hz passband)",
    users: "NATO forces",
    visualId: "Solid block of noise with distinct edges, preamble tones at start",
  },
  {
    id: "ale2g",
    name: "2G ALE",
    standard: "MIL-STD-188-141A",
    description: "Automatic Link Establishment using 8-tone MFSK. Automates frequency selection based on ionospheric conditions.",
    bandwidth: "~3 kHz",
    users: "USA, NATO, PLA, Israel, Japan",
    visualId: "Distinctive chirp sound, easily recognized on waterfall",
  },
  {
    id: "ale3g",
    name: "3G ALE",
    standard: "STANAG 4538",
    description: "Fast, robust linking protocol for high-priority traffic.",
    bandwidth: "~6 kHz",
    users: "NATO, USA",
    visualId: "Wider, synchronized bursts of data",
  },
  {
    id: "t600",
    name: "T-600",
    standard: "Russian FSK",
    description: "50 Baud Frequency Shift Keying mode used by Russian strategic networks.",
    bandwidth: "~500 Hz",
    users: "Russian Federation",
    visualId: "Narrow FSK signal with steady shift",
  },
  {
    id: "at3104",
    name: "AT-3104",
    standard: "Russian Multi-tone PSK",
    description: "Complex multi-tone PSK modem with 12 or 20 carriers for robust data transmission.",
    bandwidth: "~3 kHz",
    users: "Russian Federation",
    visualId: "Multiple parallel tones visible on waterfall",
  },
  {
    id: "othr",
    name: "29B6 Container",
    standard: "Russian OTHR",
    description: "Bi-static Over-the-Horizon Radar sweeping 6–26 MHz for aircraft/missile detection.",
    bandwidth: "Wideband sweep",
    users: "Russian Federation",
    visualId: "Repetitive 10–50 Hz thump, helicopter-like noise",
  },
];

export const MILITARY_FREQUENCIES: MilitaryFrequency[] = [
  // === LF BAND ===
  {
    id: "chayka",
    frequency: "100 kHz",
    frequencyKhz: 100,
    system: "Chayka",
    designation: "Loran-C Counterpart",
    operator: "Russia",
    band: "LF",
    signalType: "navigation",
    description: "Russian military navigation and timing synchronization. Terrestrial fallback for GPS-denied environments.",
    classification: "Strategic",
    power: "Megawatt-class",
    notes: "High-intensity pulse trains at specific GRIs. Can overload sensitive SDR front-ends.",
  },
  {
    id: "ndb-ytr",
    frequency: "215 kHz",
    frequencyKhz: 215,
    system: "NDB",
    designation: "YTR",
    operator: "Canada",
    band: "LF",
    signalType: "beacon",
    description: "Military Non-Directional Beacon at CFB Trenton, Ontario.",
    classification: "Navigation",
    power: "100W",
    location: "CFB Trenton, Ontario",
  },
  {
    id: "ndb-da",
    frequency: "223 kHz",
    frequencyKhz: 223,
    system: "NDB",
    designation: "DA",
    operator: "USA",
    band: "LF",
    signalType: "beacon",
    description: "Military NDB at Davison Army Airfield, Fort Belvoir.",
    classification: "Navigation",
    power: "50W",
    location: "Fort Belvoir, Virginia",
  },
  {
    id: "ndb-dd",
    frequency: "253 kHz",
    frequencyKhz: 253,
    system: "NDB",
    designation: "DD",
    operator: "USA",
    band: "LF",
    signalType: "beacon",
    description: "Military NDB at Rickenbacker ANG Base, Ohio.",
    classification: "Navigation",
    power: "25W",
    location: "Rickenbacker ANG Base, Ohio",
  },
  {
    id: "ndb-ab",
    frequency: "360 kHz",
    frequencyKhz: 360,
    system: "NDB",
    designation: "AB",
    operator: "Russia",
    band: "MF",
    signalType: "beacon",
    description: "Military/Dual Use NDB at Abakan.",
    classification: "Navigation",
    location: "Abakan, Russia",
  },
  {
    id: "ndb-ft",
    frequency: "365 kHz",
    frequencyKhz: 365,
    system: "NDB",
    designation: "FT",
    operator: "USA",
    band: "MF",
    signalType: "beacon",
    description: "High-power military NDB at NAS JRB Fort Worth, Texas.",
    classification: "Navigation",
    power: "400W (High)",
    location: "NAS JRB Fort Worth, Texas",
  },
  {
    id: "ndb-wlm",
    frequency: "365 kHz",
    frequencyKhz: 365,
    system: "NDB",
    designation: "WLM",
    operator: "Australia",
    band: "MF",
    signalType: "beacon",
    description: "High-power military NDB at RAAF Base Williamtown.",
    classification: "Navigation",
    power: "3000W (High)",
    location: "RAAF Base Williamtown, Australia",
  },
  {
    id: "ndb-km",
    frequency: "690 kHz",
    frequencyKhz: 690,
    system: "NDB",
    designation: "KM",
    operator: "Russia",
    band: "MF",
    signalType: "beacon",
    description: "NDB at Arkhangelsk Strategic Bomber Base.",
    classification: "Strategic",
    location: "Arkhangelsk, Russia",
  },
  // === VLF/LF Submarine Command ===
  {
    id: "nwc",
    frequency: "19.8 kHz",
    frequencyKhz: 19.8,
    system: "VLF Submarine Command",
    designation: "NWC",
    operator: "Australia",
    band: "LF",
    signalType: "digital",
    description: "North West Cape VLF station — US/Australian Navy submarine command link.",
    classification: "Strategic",
    power: "Megawatt-class",
    location: "North West Cape, Australia",
    notes: "Harmonics bleed into LF range",
  },
  {
    id: "naa",
    frequency: "24.0 kHz",
    frequencyKhz: 24,
    system: "VLF Submarine Command",
    designation: "NAA",
    operator: "USA",
    band: "LF",
    signalType: "digital",
    description: "Cutler, Maine — The most powerful VLF station in the world. Sends encrypted data to SSBNs.",
    classification: "Strategic",
    power: "Megawatt-class",
    location: "Cutler, Maine",
    notes: "MSK/FSK encrypted data to ballistic missile submarines",
  },
  {
    id: "nrk",
    frequency: "37.5 kHz",
    frequencyKhz: 37.5,
    system: "VLF Submarine Command",
    designation: "NRK/TFK",
    operator: "NATO",
    band: "LF",
    signalType: "digital",
    description: "Grindavik, Iceland — Critical for North Atlantic submarine operations.",
    classification: "Strategic",
    power: "Megawatt-class",
    location: "Grindavik, Iceland",
  },
  {
    id: "rbu",
    frequency: "66.66 kHz",
    frequencyKhz: 66.66,
    system: "Time Signal",
    designation: "RBU",
    operator: "Russia",
    band: "LF",
    signalType: "beacon",
    description: "Moscow precision time signals for military unit synchronization.",
    classification: "Strategic",
    location: "Moscow, Russia",
  },
  // === MF BAND ===
  {
    id: "navtex-local",
    frequency: "490 kHz",
    frequencyKhz: 490,
    system: "NAVTEX",
    designation: "National/Local",
    operator: "International",
    band: "MF",
    signalType: "digital",
    description: "NAVTEX national/local language broadcasts. SITOR-B digital mode with navigational warnings.",
    classification: "Navigation",
    notes: "NAVAREA warnings detail military firing exercises, submarine cable ops, closed zones",
  },
  {
    id: "navtex-intl",
    frequency: "518 kHz",
    frequencyKhz: 518,
    system: "NAVTEX",
    designation: "International",
    operator: "International",
    band: "MF",
    signalType: "digital",
    description: "International NAVTEX broadcasts. Intelligence value in NAVAREA warnings.",
    classification: "Navigation",
  },
  {
    id: "baltic-2166",
    frequency: "2166 kHz",
    frequencyKhz: 2166,
    system: "Russian Navy Fleet Broadcast",
    designation: "Baltic Fleet",
    operator: "Russia",
    band: "MF",
    signalType: "broadcast",
    description: "Baltic Fleet (Kaliningrad) night-time radiogram traffic.",
    classification: "Tactical",
    location: "Kaliningrad, Russia",
    notes: "Active during nighttime hours",
  },
  {
    id: "distress-2182",
    frequency: "2182 kHz",
    frequencyKhz: 2182,
    system: "International Distress",
    designation: "Distress/Hailing",
    operator: "International",
    band: "MF",
    signalType: "voice",
    description: "International Distress frequency. Guarded by all naval vessels. Primary inter-navy hailing frequency.",
    classification: "Strategic",
    notes: "Used for 'Dangerous Military Activities' coordination",
  },
  {
    id: "baltic-2219",
    frequency: "2219 kHz",
    frequencyKhz: 2219,
    system: "Russian Navy Fleet Broadcast",
    designation: "Baltic Fleet",
    operator: "Russia",
    band: "MF",
    signalType: "broadcast",
    description: "Baltic Fleet (Kaliningrad) night-time radiogram traffic.",
    classification: "Tactical",
    location: "Kaliningrad, Russia",
  },
  {
    id: "blacksea-2525",
    frequency: "2525 kHz",
    frequencyKhz: 2525,
    system: "Russian Navy Fleet Broadcast",
    designation: "Black Sea Fleet",
    operator: "Russia",
    band: "MF",
    signalType: "broadcast",
    description: "Black Sea Fleet (Sevastopol) regional coverage.",
    classification: "Tactical",
    location: "Sevastopol, Russia",
  },
  {
    id: "blacksea-2776",
    frequency: "2776 kHz",
    frequencyKhz: 2776,
    system: "Russian Navy Fleet Broadcast",
    designation: "Black Sea Fleet",
    operator: "Russia",
    band: "MF",
    signalType: "broadcast",
    description: "Black Sea Fleet (Sevastopol) regional coverage.",
    classification: "Tactical",
    location: "Sevastopol, Russia",
  },
  // === HF BAND - US HFGCS ===
  {
    id: "hfgcs-4724",
    frequency: "4724.0 kHz",
    frequencyKhz: 4724,
    system: "HFGCS",
    designation: "Mainsail (Night)",
    operator: "USA",
    band: "HF",
    signalType: "voice",
    description: "USAF High Frequency Global Communications System — Night/Short Range backup.",
    classification: "Strategic",
    notes: "Callsign: MAINSAIL. Carries Skyking EAMs.",
  },
  {
    id: "hfgcs-6739",
    frequency: "6739.0 kHz",
    frequencyKhz: 6739,
    system: "HFGCS",
    designation: "Mainsail (Night)",
    operator: "USA",
    band: "HF",
    signalType: "voice",
    description: "USAF HFGCS Night/Short Range backup frequency.",
    classification: "Strategic",
  },
  {
    id: "hfgcs-8992",
    frequency: "8992.0 kHz",
    frequencyKhz: 8992,
    system: "HFGCS",
    designation: "Mainsail (Primary)",
    operator: "USA",
    band: "HF",
    signalType: "voice",
    description: "USAF HFGCS Primary frequency — one of the most active military frequencies in the world.",
    classification: "Strategic",
    notes: "Guarded 24/7. TACAMO & Looking Glass maintain constant guard.",
  },
  {
    id: "hfgcs-11175",
    frequency: "11175.0 kHz",
    frequencyKhz: 11175,
    system: "HFGCS",
    designation: "Mainsail (Primary)",
    operator: "USA",
    band: "HF",
    signalType: "voice",
    description: "USAF HFGCS Primary frequency — carries Emergency Action Messages (EAMs).",
    classification: "Strategic",
    notes: "Skyking messages: nuclear execution orders, bomber retargeting, or test drills.",
  },
  {
    id: "eam-11244",
    frequency: "11244.0 kHz",
    frequencyKhz: 11244,
    system: "HFGCS",
    designation: "EAM Dedicated",
    operator: "USA",
    band: "HF",
    signalType: "voice",
    description: "Dedicated Emergency Action Message (EAM) broadcast frequency.",
    classification: "Strategic",
    notes: "Skyking broadcasts only",
  },
  {
    id: "hfgcs-13200",
    frequency: "13200.0 kHz",
    frequencyKhz: 13200,
    system: "HFGCS",
    designation: "Mainsail (Day)",
    operator: "USA",
    band: "HF",
    signalType: "voice",
    description: "USAF HFGCS Day/Long Range frequency.",
    classification: "Strategic",
  },
  {
    id: "hfgcs-15016",
    frequency: "15016.0 kHz",
    frequencyKhz: 15016,
    system: "HFGCS",
    designation: "Mainsail (Day)",
    operator: "USA",
    band: "HF",
    signalType: "voice",
    description: "USAF HFGCS Day/Long Range frequency.",
    classification: "Strategic",
  },
  // US SIPR/NIPR ALE
  {
    id: "sipr-3113",
    frequency: "3113.0 kHz",
    frequencyKhz: 3113,
    system: "SIPR HF ALE",
    designation: "Secret Network",
    operator: "USA",
    band: "HF",
    signalType: "digital",
    description: "Secret Internet Protocol Router (SIPR) HF ALE network.",
    classification: "Strategic",
  },
  {
    id: "sipr-5702",
    frequency: "5702.0 kHz",
    frequencyKhz: 5702,
    system: "SIPR HF ALE",
    designation: "Secret Network",
    operator: "USA",
    band: "HF",
    signalType: "digital",
    description: "SIPR HF ALE network frequency.",
    classification: "Strategic",
  },
  {
    id: "sipr-8968",
    frequency: "8968.0 kHz",
    frequencyKhz: 8968,
    system: "SIPR HF ALE",
    designation: "Secret Network",
    operator: "USA",
    band: "HF",
    signalType: "digital",
    description: "SIPR HF ALE network frequency.",
    classification: "Strategic",
  },
  {
    id: "sipr-11181",
    frequency: "11181.0 kHz",
    frequencyKhz: 11181,
    system: "SIPR HF ALE",
    designation: "Secret Network",
    operator: "USA",
    band: "HF",
    signalType: "digital",
    description: "SIPR HF ALE network frequency.",
    classification: "Strategic",
  },
  // === HF BAND - RUSSIA ===
  {
    id: "buzzer",
    frequency: "4625 kHz",
    frequencyKhz: 4625,
    system: "UVB-76",
    designation: "The Buzzer",
    operator: "Russia",
    band: "HF",
    signalType: "marker",
    description: "The most famous Russian marker station. Buzzing tone ~25 times/minute, interrupted for live voice messages.",
    classification: "Strategic",
    location: "Western Military District",
    notes: "24/7 operation. Channel reservation for high-priority Monolith messages.",
  },
  {
    id: "pip-day",
    frequency: "5448 kHz",
    frequencyKhz: 5448,
    system: "The Pip",
    designation: "The Pip (Day)",
    operator: "Russia",
    band: "HF",
    signalType: "marker",
    description: "Russian marker station transmitting short beeps. Serves Southern Military District.",
    classification: "Strategic",
    notes: "Night frequency: 3756 kHz",
  },
  {
    id: "pip-night",
    frequency: "3756 kHz",
    frequencyKhz: 3756,
    system: "The Pip",
    designation: "The Pip (Night)",
    operator: "Russia",
    band: "HF",
    signalType: "marker",
    description: "Russian marker station (night frequency). Southern Military District.",
    classification: "Strategic",
  },
  {
    id: "squeaky-day",
    frequency: "5367 kHz",
    frequencyKhz: 5367,
    system: "The Squeaky Wheel",
    designation: "Squeaky Wheel (Day)",
    operator: "Russia",
    band: "HF",
    signalType: "marker",
    description: "Russian marker station transmitting distinct high-pitched squeaks.",
    classification: "Strategic",
    notes: "Night frequency: 3363.5 kHz",
  },
  {
    id: "squeaky-night",
    frequency: "3363.5 kHz",
    frequencyKhz: 3363.5,
    system: "The Squeaky Wheel",
    designation: "Squeaky Wheel (Night)",
    operator: "Russia",
    band: "HF",
    signalType: "marker",
    description: "Russian marker station (night frequency).",
    classification: "Strategic",
  },
  // Russian Navy Single Letter Beacons
  {
    id: "slb-3594",
    frequency: "3594 kHz cluster",
    frequencyKhz: 3594,
    system: "Single Letter Beacons",
    designation: "C/S/D/P/F",
    operator: "Russia",
    band: "HF",
    signalType: "beacon",
    description: "Russian Navy propagation beacons: C (Moscow), S (Severomorsk), D (Sevastopol), P (Kaliningrad), F (Vladivostok).",
    classification: "Tactical",
    notes: "Clustered in 100 Hz increments around center frequency",
  },
  {
    id: "slb-4557",
    frequency: "4557 kHz cluster",
    frequencyKhz: 4557,
    system: "Single Letter Beacons",
    designation: "C/S/D/P/F",
    operator: "Russia",
    band: "HF",
    signalType: "beacon",
    description: "Russian Navy Single Letter Beacon cluster — propagation analysis network.",
    classification: "Tactical",
  },
  {
    id: "slb-7508",
    frequency: "7508 kHz cluster",
    frequencyKhz: 7508,
    system: "Single Letter Beacons",
    designation: "C/S/D/P/F",
    operator: "Russia",
    band: "HF",
    signalType: "beacon",
    description: "Russian Navy Single Letter Beacon cluster.",
    classification: "Tactical",
  },
  {
    id: "slb-10871",
    frequency: "10871 kHz cluster",
    frequencyKhz: 10871,
    system: "Single Letter Beacons",
    designation: "C/S/D/P/F",
    operator: "Russia",
    band: "HF",
    signalType: "beacon",
    description: "Russian Navy Single Letter Beacon cluster.",
    classification: "Tactical",
  },
  // RDL Strategic Network
  {
    id: "rdl-3244",
    frequency: "3244 kHz",
    frequencyKhz: 3244,
    system: "RDL Monolith Network",
    designation: "Strategic Broadcast",
    operator: "Russia",
    band: "HF",
    signalType: "digital",
    description: "Russian strategic broadcast system carrying Monolith command messages.",
    classification: "Strategic",
    notes: "Uses T-600 (50 Baud FSK) and AT-3104 (multi-tone PSK)",
  },
  {
    id: "rdl-4445",
    frequency: "4445 kHz",
    frequencyKhz: 4445,
    system: "RDL Monolith Network",
    designation: "Strategic Broadcast",
    operator: "Russia",
    band: "HF",
    signalType: "digital",
    description: "RDL network frequency for strategic command messages.",
    classification: "Strategic",
  },
  {
    id: "rdl-5268",
    frequency: "5268 kHz",
    frequencyKhz: 5268,
    system: "RDL Monolith Network",
    designation: "Strategic Broadcast",
    operator: "Russia",
    band: "HF",
    signalType: "digital",
    description: "RDL network frequency.",
    classification: "Strategic",
  },
  {
    id: "rdl-6342",
    frequency: "6342 kHz",
    frequencyKhz: 6342,
    system: "RDL Monolith Network",
    designation: "Strategic Broadcast",
    operator: "Russia",
    band: "HF",
    signalType: "digital",
    description: "RDL network frequency.",
    classification: "Strategic",
  },
  {
    id: "rdl-8136",
    frequency: "8136 kHz",
    frequencyKhz: 8136,
    system: "RDL Monolith Network",
    designation: "Strategic Broadcast",
    operator: "Russia",
    band: "HF",
    signalType: "digital",
    description: "RDL network frequency.",
    classification: "Strategic",
  },
  {
    id: "rdl-10535",
    frequency: "10535 kHz",
    frequencyKhz: 10535,
    system: "RDL Monolith Network",
    designation: "Strategic Broadcast",
    operator: "Russia",
    band: "HF",
    signalType: "digital",
    description: "RDL network frequency.",
    classification: "Strategic",
  },
  // === HF BAND - PLA (China) ===
  {
    id: "pla-m89-3197",
    frequency: "3197 kHz",
    frequencyKhz: 3197,
    system: "PLA Rocket Force M89",
    designation: "M89 (Morse CW)",
    operator: "China",
    band: "HF",
    signalType: "numbers",
    description: "PLA Rocket Force massive CW network — coded messages to missile brigades.",
    classification: "Strategic",
    notes: "Highly redundant C2 structure",
  },
  {
    id: "pla-m89-4523",
    frequency: "4523 kHz",
    frequencyKhz: 4523,
    system: "PLA Rocket Force M89",
    designation: "M89 (Morse CW)",
    operator: "China",
    band: "HF",
    signalType: "numbers",
    description: "PLA Rocket Force CW network frequency.",
    classification: "Strategic",
  },
  {
    id: "pla-v26-6719",
    frequency: "6719 kHz",
    frequencyKhz: 6719,
    system: "PLA V26 Voice",
    designation: "V26 (Numbers Station)",
    operator: "China",
    band: "HF",
    signalType: "numbers",
    description: "Female voice reading numbers with 4+4 digit callsigns. Operates parallel with M89.",
    classification: "Strategic",
  },
  {
    id: "pla-v26-8940",
    frequency: "8940 kHz",
    frequencyKhz: 8940,
    system: "PLA V26 Voice",
    designation: "V26 (Numbers Station)",
    operator: "China",
    band: "HF",
    signalType: "numbers",
    description: "PLA V26 voice numbers station frequency.",
    classification: "Strategic",
  },
  {
    id: "pla-ale-5748",
    frequency: "5748.6 kHz",
    frequencyKhz: 5748.6,
    system: "PLA 2G ALE",
    designation: "PLAAF ALE",
    operator: "China",
    band: "HF",
    signalType: "digital",
    description: "PLA Air Force 2G ALE network. Stations scan frequencies in descending order.",
    classification: "Tactical",
    notes: "Numeric station IDs (100-126, 922-928)",
  },
  {
    id: "pla-ale-9042",
    frequency: "9042 kHz",
    frequencyKhz: 9042,
    system: "PLA 2G ALE",
    designation: "PLAAF ALE",
    operator: "China",
    band: "HF",
    signalType: "digital",
    description: "PLA 2G ALE primary frequency.",
    classification: "Tactical",
  },
  // === HF BAND - ISRAEL ===
  {
    id: "iaf-5123",
    frequency: "5123 kHz",
    frequencyKhz: 5123,
    system: "IAF HF Network",
    designation: "Set 1 (USB)",
    operator: "Israel",
    band: "HF",
    signalType: "voice",
    description: "Israeli Air Force HF network for long-range strike coordination.",
    classification: "Tactical",
  },
  {
    id: "iaf-8797",
    frequency: "8797 kHz",
    frequencyKhz: 8797,
    system: "IAF HF Network",
    designation: "Set 1 (USB)",
    operator: "Israel",
    band: "HF",
    signalType: "voice",
    description: "IAF HF network frequency.",
    classification: "Tactical",
  },
  {
    id: "iaf-10642",
    frequency: "10642 kHz",
    frequencyKhz: 10642,
    system: "IAF HF Network",
    designation: "Set 3 (USB)",
    operator: "Israel",
    band: "HF",
    signalType: "voice",
    description: "IAF HF network Set 3 frequency.",
    classification: "Tactical",
  },
  // === HF BAND - JAPAN ===
  {
    id: "jsdf-3195",
    frequency: "3195 kHz",
    frequencyKhz: 3195,
    system: "JSDF HF Net",
    designation: "JJT88 (Tokyo)",
    operator: "Japan",
    band: "HF",
    signalType: "voice",
    description: "Japan Self-Defense Forces HF aerial coordination net.",
    classification: "Tactical",
    notes: "Net control JJT88 Tokyo, outstations like JJS21 Misawa",
  },
  {
    id: "jsdf-5055",
    frequency: "5055 kHz",
    frequencyKhz: 5055,
    system: "JSDF HF Net",
    designation: "JSDF",
    operator: "Japan",
    band: "HF",
    signalType: "voice",
    description: "JSDF HF net frequency for aerial coordination.",
    classification: "Tactical",
  },
  // === LOW VHF BAND ===
  {
    id: "sincgars",
    frequency: "30.000–87.975 MHz",
    frequencyKhz: 59000,
    system: "SINCGARS",
    designation: "NATO Combat Net Radio",
    operator: "NATO",
    band: "VHF",
    signalType: "voice",
    description: "Single Channel Ground and Airborne Radio System. 2320 channels at 25 kHz spacing. FM voice or frequency hopping.",
    classification: "Tactical",
    notes: "FH mode hops ~100 times/sec — appears as 'popcorn' noise on waterfall",
  },
  {
    id: "nato-tactical-30",
    frequency: "30.30–30.50 MHz",
    frequencyKhz: 30400,
    system: "NATO Harmonized",
    designation: "Tactical Band",
    operator: "NATO",
    band: "VHF",
    signalType: "voice",
    description: "NATO harmonized tactical sub-band (NJFA Type 1).",
    classification: "Tactical",
  },
  {
    id: "nato-tactical-32",
    frequency: "32.15–32.45 MHz",
    frequencyKhz: 32300,
    system: "NATO Harmonized",
    designation: "Tactical Band",
    operator: "NATO",
    band: "VHF",
    signalType: "voice",
    description: "NATO harmonized tactical sub-band.",
    classification: "Tactical",
  },
  {
    id: "nato-armor",
    frequency: "41.00–47.00 MHz",
    frequencyKhz: 44000,
    system: "NATO Harmonized",
    designation: "Primary Armor Band",
    operator: "NATO",
    band: "VHF",
    signalType: "voice",
    description: "Primary tank communications band. Wavelength penetrates forests and urban clutter.",
    classification: "Tactical",
    notes: "The 'sweet spot' for armor communications",
  },
  {
    id: "nato-airground",
    frequency: "73.30–74.10 MHz",
    frequencyKhz: 73700,
    system: "NATO Harmonized",
    designation: "Air-Ground Coordination",
    operator: "NATO",
    band: "VHF",
    signalType: "voice",
    description: "NATO Air-Ground coordination band.",
    classification: "Tactical",
  },
  {
    id: "russia-lowvhf",
    frequency: "30–50 MHz",
    frequencyKhz: 40000,
    system: "Russian Tactical",
    designation: "R-123 / R-173 Magnolia",
    operator: "Russia",
    band: "VHF",
    signalType: "voice",
    description: "Primary band for Russian armor and mechanized infantry. 'Over the hill' communication for ground maneuver.",
    classification: "Tactical",
    notes: "Soviet-legacy R-123 and R-173 radios",
  },
];

// Helper: get all unique operators
export const ALL_OPERATORS: Operator[] = ["USA", "Russia", "China", "NATO", "Israel", "Japan", "Australia", "Canada", "International"];

// Helper: get all unique signal types
export const ALL_SIGNAL_TYPES: SignalType[] = ["voice", "digital", "beacon", "navigation", "radar", "marker", "numbers", "broadcast"];

// Helper: get all unique classifications
export const ALL_CLASSIFICATIONS = ["Strategic", "Tactical", "Navigation"] as const;

// Operator colors for UI
export const OPERATOR_COLORS: Record<Operator, string> = {
  USA: "#3b82f6",
  Russia: "#ef4444",
  China: "#f59e0b",
  NATO: "#06b6d4",
  Israel: "#8b5cf6",
  Japan: "#ec4899",
  Australia: "#22c55e",
  Canada: "#f97316",
  International: "#94a3b8",
};

// Operator flag emojis for compact display
export const OPERATOR_FLAGS: Record<Operator, string> = {
  USA: "US",
  Russia: "RU",
  China: "CN",
  NATO: "NATO",
  Israel: "IL",
  Japan: "JP",
  Australia: "AU",
  Canada: "CA",
  International: "INTL",
};
